version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: dockerfile
    depends_on:
      - "db"
    tty: true
    ports:
      - "1323:1323"
    volumes:
      - ./db:/app/db
    logging:
      options:
        max-size: 50m
