version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    ports:
      - "1323:1323"
    volumes:
      - ./db:/app/db
    logging:
      options:
        max-size: 50m
    restart: always

  localtunnel:
    build:
      context: .
      dockerfile: dockerfile-serve
    restart: on-failure
    tty: true
    depends_on:
      - go
    links:
      - go
