version: "3.9"
services:
  go:
    build:
      context: .
      dockerfile: dockerfile
    tty: true
    ports:
      - "1323:1323"
    volumes:
      - ./db:/app/db
    logging:
      options:
        max-size: 50m
    restart: always

  ngrok:
    image: shkoliar/ngrok:latest
    tty: true
    ports:
      - 4551:4551
    links:
      - go
    environment:
      - PORT=1323
      - DOMAIN=go
      - DEBUG=true
      - AUTH_TOKEN=<ngrok auth token>
    restart: always
