env:
  browser: true
  es2021: true
extends:
  - plugin:react/recommended
  - google
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - react-hooks
rules:
  {
    "react-hooks/rules-of-hooks": "error",
    "react-hooks/exhaustive-deps": "warn",
    "max-len": ["error", { "code": 120 }],
    "indent": ["error", 4],
  }
